/* Create Table for Preivous_Application Data */

\connect home_credit_default_risk;

CREATE TABLE previous_application(
  SK_ID_PREV INT,
  SK_ID_CURR INT,
  NAME_CONTRACT_TYPE VARCHAR,
  AMT_ANNUITY DECIMAL,
  AMT_APPLICATION DECIMAL,
  AMT_CREDIT DECIMAL,
  AMT_DOWN_PAYMENT DECIMAL,
  AMT_GOODS_PRICE DECIMAL,
  WEEKDAY_APPR_PROCESS_START VARCHAR,
  HOUR_APPR_PROCESS_START INT,
  FLAG_LAST_APPL_PER_CONTRACT VARCHAR,
  NFLAG_LAST_APPL_IN_DAY INT,
  RATE_DOWN_PAYMENT DECIMAL,
  RATE_INTEREST_PRIMARY DECIMAL,
  RATE_INTEREST_PRIVILEGED DECIMAL,
  NAME_CASH_LOAN_PURPOSE VARCHAR,
  NAME_CONTRACT_STATUS VARCHAR,
  DAYS_DECISION INT,
  NAME_PAYMENT_TYPE VARCHAR,
  CODE_REJECT_REASON VARCHAR,
  NAME_TYPE_SUITE VARCHAR,
  NAME_CLIENT_TYPE VARCHAR,
  NAME_GOODS_CATEGORY VARCHAR,
  NAME_PORTFOLIO VARCHAR,
  NAME_PRODUCT_TYPE VARCHAR,
  CHANNEL_TYPE VARCHAR,
  SELLERPLACE_AREA INT,
  NAME_SELLER_INDUSTRY VARCHAR,
  CNT_PAYMENT DECIMAL,
  NAME_YIELD_GROUP VARCHAR,
  PRODUCT_COMBINATION VARCHAR,
  DAYS_FIRST_DRAWING DECIMAL,
  DAYS_FIRST_DUE DECIMAL,
  DAYS_LAST_DUE_1ST_VERSION DECIMAL,
  DAYS_LAST_DUE DECIMAL,
  DAYS_TERMINATION DECIMAL,
  NFLAG_INSURED_ON_APPROVAL DECIMAL
);

/* Import .csv data into this table from local computer */
\COPY previous_application FROM '/Users/kbajina/Documents/DATA SCIENCE/Metis | Data Science Bootcamp/Metis Project Portfolio/Metis-Proj-3-classification/data_files/home-credit-default-risk/previous_application.csv' DELIMITER ',' CSV HEADER;
